table Customers
	lineageTag: 6a6fff8a-bb65-446c-b6ad-c15b5d81d372

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: f19e6ad0-239e-4658-bff5-df943fb6234a
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column Prefix
		dataType: string
		lineageTag: 8e465ddf-ed6b-4ed8-8e79-f5d1d34d6c5e
		summarizeBy: none
		sourceColumn: Prefix

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 647fe8de-d675-4c0e-abfe-3960a9fe1087
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: ffb0b1cf-bcf3-4f18-bcf9-8680d4cc25b7
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 788a198e-4982-4a69-8615-fa69bfc2b537
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variation
			isDefault
			relationship: ba287328-1167-4a9a-abc2-31854135e1f2
			defaultHierarchy: LocalDateTable_9e9210f4-bff5-44f6-a226-27969893be86.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: af67f7a8-5e77-46b7-9803-f7b16eb2829a
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: c2cfe540-7970-49a9-8347-71ff312da34a
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: e4536083-d378-4230-be25-ccfffc7bf702
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column AnnualIncome
		dataType: int64
		formatString: 0
		lineageTag: 486f5790-a5ca-4d9d-a22a-fa5a39578bca
		summarizeBy: sum
		sourceColumn: AnnualIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: bfada3ee-7395-4ffa-8a57-fa411fab7b1a
		summarizeBy: sum
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: d7dd8d9e-c954-4718-a7d2-58b0fcaceb4d
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: a116da64-2117-459f-bbca-943feb5ecb32
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column HomeOwner
		dataType: string
		lineageTag: 558a7b0c-25c6-4dce-b9bf-685fb2e5ef69
		summarizeBy: none
		sourceColumn: HomeOwner

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\OneDrive\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Dashboard\data\Customer.csv"),[Delimiter=",", Columns=13, Encoding=1251, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"Prefix", type text}, {"FirstName", type text}, {"LastName", type text}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Gender", type text}, {"EmailAddress", type text}, {"AnnualIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"EducationLevel", type text}, {"Occupation", type text}, {"HomeOwner", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"CustomerKey"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each [CustomerKey] <> null and [CustomerKey] <> "")
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

