table 'RFM cats'
	lineageTag: cffacad1-2ed3-47bc-b50d-dadf55b37230

	column Значение
		dataType: int64
		formatString: 0
		lineageTag: f667db6e-2b9e-4783-aa60-c05496578089
		summarizeBy: none
		sourceColumn: Значение

		annotation SummarizationSetBy = Automatic

	column 'Определение сегмента'
		dataType: string
		lineageTag: e1b11e94-c684-469e-8857-ea743d8ac04a
		summarizeBy: none
		sourceColumn: Определение сегмента

		annotation SummarizationSetBy = Automatic

	column 'Определение группы'
		dataType: string
		lineageTag: c7de6d5e-9468-45ee-b35e-8a9e59a8732f
		summarizeBy: none
		sourceColumn: Определение группы

		annotation SummarizationSetBy = Automatic

	partition 'RFM cats' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\User\OneDrive\Рабочий стол\Dashboard\data\rfm_categories.xlsx"), null, true),
				    #"Таблица 1_Sheet" = Source{[Item="Таблица 1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Таблица 1_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Значение", Int64.Type}, {"Определение сегмента", type text}, {"Определение группы", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

