table 'Sales data'
	lineageTag: ae5ad7fb-f31e-4b51-99de-de1ffd75587e

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6ff2eaa2-f300-47e4-9910-6f02514cd4b1
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StockDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4097b9fa-eebb-4cf1-b72c-d940f19050ef
		summarizeBy: none
		sourceColumn: StockDate

		variation Variation
			isDefault
			relationship: a7a521b6-69c1-48d4-92dd-d7fed8d599e1
			defaultHierarchy: LocalDateTable_884963bb-e511-4762-80bc-efa1d65c547a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderNumber
		dataType: string
		lineageTag: b78cba33-fb24-426e-b791-0354424002cb
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 76c5005c-46d0-48d1-8233-3ee17c71fe73
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 7b238b73-39ab-480b-b437-1e64194bc743
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: c7fda829-3252-44af-83f9-2267c3073b8e
		summarizeBy: count
		sourceColumn: TerritoryKey

		annotation SummarizationSetBy = Automatic

	column OrderLineItem
		dataType: int64
		formatString: 0
		lineageTag: 859e98fa-d5d2-48bd-b1fb-39192d3d011c
		summarizeBy: sum
		sourceColumn: OrderLineItem

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: fe829cdf-24f1-4e5a-bb8e-fa8d52018428
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	partition 'Sales data' = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\User\OneDrive\Рабочий стол\Dashboard\data"),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Name] = "Sales Data 2020.csv" or [Name] = "Sales Data 2021.csv" or [Name] = "Sales Data 2022.csv")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Content"}),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Removed Other Columns", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"OrderDate", type date}, {"StockDate", type date}, {"OrderNumber", type text}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"TerritoryKey", Int64.Type}, {"OrderLineItem", Int64.Type}, {"OrderQuantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

